# .github/workflows/auto-merge.yaml
name: Merge Preview to Master
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to merge to master'
        required: true
        default: 'preview'
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Only run on preview
        if: github.ref_name == 'preview'
        run: |
          echo "ERROR: This manual workflow can only be run from the 'preview' branch."
          exit 1

      - uses: actions/checkout@v4

      - name: test echo
        run: |
          echo "${{inputs.branch}}"

      - name: test merge
        run: |
          echo "attempting merge"
          git branch
