# .github/workflows/auto-merge.yaml
name: Merge Preview to Master
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Only run on preview
        if: github.ref_name != 'master'
        run: |
          echo "ERROR: This manual workflow can only be run from the 'master' branch."
          exit 1

      - uses: actions/checkout@v4
        with:
          # Possible optimization here: target fetch to only master
          fetch-depth: 0

      - name: Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge preview into master locally
        run: |
          git pull origin preview
          git merge preview -m "GHA - Merge preview to master"

      - name: Update 'preview' branch to prevent PR from closing
        run: |
          git checkout preview
          echo $RANDOM > random.txt
          git add *
          git commit -m "GHA - Update preview branch"
          git push

      - name: Push merge to master
        run: |
          git checkout master
          git push
